config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  resources :lists, only: [:new, :create, :show, :index, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "Ce film existe déjà dans la liste." }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: :create
  before_action :set_bookmark, only: [:edit, :update, :destroy]

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      flash.notice = "Film ajouté à #{@list.name}"
      redirect_to list_path(@list, anchor: "bookmark-#{@bookmark.id}")
    else
      flash.alert = "Erreur: impossible d'ajouter le film."
      redirect_to 'lists/show'
    end
  end

  def edit
  end

  def update
    @bookmark.update(bookmark_params)
    if @bookmark.save
      flash.notice = "Film modifié !"
      redirect_to list_path(@bookmark.list, anchor: "bookmark-#{@bookmark.id}")
    else
      flash.alert = "Erreur: modification annulée."
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = current_user.lists.includes(:movies)
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      flash.notice = "Votre liste a été créée !"
      redirect_to list_path(@list)
    else
      flash.alert = "Erreur: votre liste ne peut être créée."
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/lists/new' # Or :prefix_to_your_route
  end

  def after_inactive_sign_up_path_for(resource)
    '/lists/new' # Or :prefix_to_your_route
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-8 mt-5">
      <div class="block-form">
        <h1>Modifier le film</h1>
          <%= simple_form_for @bookmark do |f| %>
          <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Titre de film", label: "Film à ajouter" %>
          <%= f.input :comment, label: "Commentaire" %>
          <%= f.submit "Modifier le film", class: "btn btn-first" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/partial/_bookmark-card.html.erb
<div class="col-12 col-md-6">
  <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
  <div class="bookmark-card" id="bookmark-<%= bookmark.id %>">
    <figure>
      <%= image_tag movie.poster_url %>
    </figure>
    <div class="bookmark-body">
      <h3><%= movie.title %></h3>
      <p><%= movie.overview.truncate(140) %></p>
      <p class="rating"><i class="fas fa-star"></i><%= movie.rating %></p>
      <article>
        <p><%= bookmark.comment %></p>
        <div class="d-flex justify-content-end align-items-center">
          <%= link_to edit_bookmark_path(bookmark), class:"e-btn" do %>
            <i class="fas fa-pen"></i>
          <% end %>
          <%= link_to bookmark_path(bookmark), method: :delete, data: { confirm: "Voulez-vous supprimer '#{movie.title}' de #{@list.name} ?"}, class:"d-btn" do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieFlix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class="<%= "#{controller_name} #{action_name}" %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container mt-5">
  <h1>Mes listes</h1>
  <h2>Hello <%= current_user.username %> 👋 !</h2>
  <p>Vous avez <%= current_user.lists.count %> liste(s).</p>
  <div class="mt-4 mb-5">
    <%= link_to "Créer une liste", new_list_path, class: "btn btn-first" %>
  </div>
</div>
<% unless @lists.empty? %>
  <section class="my-lists">
    <div class="container">
      <div class="row">
        <% @lists.each do |list| %>
          <%= render "lists/partial/list-card", list: list %>
        <% end %>
      </div>
    </div>
  </section>
<% end %>

app/views/lists/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-8 mt-5">
      <div class="block-form">
        <h1>Je crée ma liste</h1>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, label: "Nom de la liste", placeholder: "Western, Drame, etc." %>
          <%= f.input :photo, as: :file, label: "Image d'illustration" %>
          <%= f.submit 'Créer ma liste', class:"btn btn-first mt-4"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/partial/_list-card.html.erb
<div class="col-12 col-md-6 col-lg-4">
  <div class="list-card" style="background-image: linear-gradient(rgba(20,24,28,0.4),rgba(20,24,28,0.4)), url('<%= cl_image_path list.photo.key %>');">
    <h3><%= list.name %></h3>

    <%# Delete link %>
    <div class="d-flex justify-content-between align-items-end">
      <% if list.user == current_user %>
        <%= link_to list_path(list), method: :delete, data: { confirm: "Voulez vous supprimer la liste #{list.name} ?"}, class: "d-btn" do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      <% end %>
      <% unless list.movies.empty? %>
        <ul>
          <% list.movies.order(created_at: :desc).limit(3).each do |movie| %>
            <li style="background-image: url('<%= image_path movie.poster_url %>');"></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <%= link_to "", list_path(list), class: "link-card" %>
  </div>
</div>

app/views/lists/show.html.erb
<%= render "shared/banner-list", list: @list %>
<section class="py-5 bookmarks">
  <div class="container">
    <% if @list.movies.empty? %>
      <p>Cette liste est vide. Vous pouvez ajouter des films</p>
    <% else %>
      <div class="row">
        <% @list.movies.each do |movie| %>
          <%= render 'bookmarks/partial/bookmark-card', movie: movie  %>
        <% end %>
      </div>
    <% end %>
  </div>
</section>
<section class="add-bookmarks">
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-8">
        <div class="block-form">
        <h2>Ajouter un film</h2>
        <%= render 'shared/form', list: @list, bookmark: @bookmark %>
      </div>
    </div>
  </div>
</section>

app/views/pages/home.html.erb
<div class="hero">
  <div class="container">
    <h1>Tous vos films préférés au même endroit</h1>
    <h2>Créez des listes et ajoutez y vos critiques</h2>
    <% if user_signed_in? %>
      <%= link_to new_list_path, class: "btn btn-first" do %>
        <i class="fas fa-plus"></i>Créer une liste
      <% end %>
    <% else %>
      <%= link_to new_user_registration_path, class: "btn btn-first" do %>
        <i class="fas fa-plus"></i>Créer une liste
      <% end %>
    <% end %>
  </div>
  <div class="wrapper"></div>
</div>
<section class="body-home">
  <div class="container">
    <h4>Des listes personnalisées à partager</h4>
    <div class="row">
      <%# 1st col %>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="list-card" style="background-image: linear-gradient(rgba(20,24,28,0.5),rgba(20,24,28,0.5)), url('https://source.unsplash.com/rguHxZmOF5U/600x246');">
          <h3>Western</h3>
          <div class="d-flex justify-content-end align-items-end">
            <ul>
              <li style="background-image: url('https://image.tmdb.org/t/p/w300_and_h450_bestv2/qbYgqOczabWNn2XKwgMtVrntD6P.jpg');"></li>
              <li style="background-image: url('https://image.tmdb.org/t/p/w300_and_h450_bestv2/zZhp7p8qvfVrSLKpOFHcKjpEj8f.jpg');"></li>
              <li style="background-image: url('https://image.tmdb.org/t/p/w300_and_h450_bestv2/oDpDXln1x3sbnt8wQBKsU6J5txT.jpg');"></li>
            </ul>
          </div>
        </div>
      </div>
      <%# 2nd col %>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="list-card" style="background-image: linear-gradient(rgba(20,24,28,0.5),rgba(20,24,28,0.5)), url('https://images.unsplash.com/reserve/Af0sF2OS5S5gatqrKzVP_Silhoutte.jpg?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=600&q=80');">
          <h3>Rom-Com</h3>
          <div class="d-flex justify-content-end align-items-end">
            <ul>
              <li style="background-image: url('https://image.tmdb.org/t/p/w300_and_h450_bestv2/3wkbKeowUp1Zpkw1KkBqMWbt0P9.jpg');"></li>
              <li style="background-image: url('https://image.tmdb.org/t/p/w300_and_h450_bestv2/cBpef6K40Su2CcBb3c18WdwRFCL.jpg');"></li>
              <li style="background-image: url('https://image.tmdb.org/t/p/w300_and_h450_bestv2/ujERk3aKABXU3NDXOAxEQYTHe9A.jpg');"></li>
            </ul>
          </div>
        </div>
      </div>
      <%# 3rd col %>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="list-card" style="background-image: linear-gradient(rgba(20,24,28,0.5),rgba(20,24,28,0.5)), url('https://images.unsplash.com/photo-1524008279394-3aed4643b30b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZGlzbmV5fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60);">
          <h3>Disney</h3>
          <div class="d-flex justify-content-end align-items-end">
            <ul>
              <li style="background-image: url('https://image.tmdb.org/t/p/w300_and_h450_bestv2/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg');"></li>
              <li style="background-image: url('https://image.tmdb.org/t/p/w300_and_h450_bestv2/a0Syo09bmNJgehjfeVL6meR9Mjh.jpg');"></li>
              <li style="background-image: url('https://image.tmdb.org/t/p/w300_and_h450_bestv2/16JPL3c6ET7ibfO35WjjWxCaVmj.jpg');"></li>
            </ul>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/shared/_banner-list.html.erb
<section class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path list.photo.key %>');">
  <div class="container">
    <h1><%= list.name %></h1>
    <%= link_to "← Voir mes listes", lists_path, class: "btn btn-first" %>
  </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Titre de film", label: "Film à ajouter" %>
  <%= f.input :comment, label: "Commentaire" %>
  <%= f.submit "Ajouter un film", class: "btn btn-first" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-movieflix.svg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "user_avatar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Voir mes listes", lists_path, class: "dropdown-item" %>
              <%= link_to "Créer une liste", new_list_path, class: "dropdown-item" %>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item logout" do %>
                <i class="fas fa-sign-out-alt"></i>Se déconnecter
              <% end %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>